### ISSUE TITLE
I met some problems in the process of DCGAN test

### ISSUE THREAD

**Issue by RobinWenqian** [qiaoguan/Person-reid-GAN-pytorch#14]
When I run main.py --option 5 --dataset myownpath --output_path myownpath, after I trained the model, it tolds me that there is **no such file test_0_0.jpg**. Where is test_0_0.jpg? And why I need test_0_0.jpg to generate new samples?  

Thank you!

**Comment by qiaoguan** [comment]
can you provide some more details such as the detailed running result

**Comment by RobinWenqian** [comment]
Ok then thank you for your quick reply.
After I ran the main.py as instructed:
![image](https://user-images.githubusercontent.com/18494091/43711960-69dbc9d8-996c-11e8-9b3c-2db77c1c0a27.png)
It told me as following:
![image](https://user-images.githubusercontent.com/18494091/43711909-3751d5fc-996c-11e8-8acf-67f3dd8c1015.png)

**Comment by qiaoguan** [comment]
检查下你的图片的路径有没什么问题？  然后把你的图片文件夹的截图发给我看看

**Comment by RobinWenqian** [comment]
在 --dataset 后面跟的路径就是和训练时候 --dataset后面跟的路径是一样的，然后--output_path 后面跟的路径就是我想让24000张图片输出到的路径。不知道这个test_0_0.jpg是什么时候有的以及在哪里。图片文件夹就按说明里写的建了一个名为data的文件夹，然后把market放在里面
![image](https://user-images.githubusercontent.com/18494091/43712614-a99b3fa2-996e-11e8-9608-2cf078a87a07.png)
谢谢！

**Comment by qiaoguan** [comment]
输出的文件夹在电脑里面有吗？  没有的画，要先新建一个文件夹，你看报错信息，有提示no directory

**Comment by RobinWenqian** [comment]
咦，输出文件夹是有的，提示的是没找到test_0_0.jpg那个文件

**Comment by qiaoguan** [comment]
在此之前，你有运行  prepare.py 和changeIndex.py这两个代码吗？   应该是你图片文件路径啥的问题把，  你仔细检查一下把，  根据报错，进去代码里面大概看一下应该就知道了

**Comment by RobinWenqian** [comment]
不好意思又来问您，我重新run了changeIndex.py,但是发现folderlimian并没有变成0，1，2，3....changeIndex.py里面除了路径之外还有需要改的地方吗？

**Comment by RobinWenqian** [comment]
嗷，我看到之前人提到的把changeIndex.py里面的两行改成关于train的就可以了

**Comment by qiaoguan** [comment]
你看一下changeIndex.py的源代码，代码很简单，很容易看懂的
