### ISSUE TITLE
problem in train_baseline.py

### ISSUE THREAD

**Issue by RobinWenqian** [qiaoguan/Person-reid-GAN-pytorch#15]
不好意思又来打扰您，之前那个DCGAN的问题都解决了很感谢您的帮助。
在运行train_baseline.py时候会有这样的报错
![image](https://user-images.githubusercontent.com/18494091/43803203-17b13c4a-9a90-11e8-8add-7a842f134566.png)
我查看了训练数据文件夹，每个训练图片的文件名应该是前面加0的。比如说报错图片里面的文件说找不到176_c6s3_042642_03.jpg，实际上应该读取的是0176_c6s3_042642_03.jpg，我该怎么改动一下train_baseline.py来让他读取时候读取的是0176_c6s3_042642_03.jpg而非176_c6s3_042642_03.jpg呢

感谢帮助

**Comment by qiaoguan** [comment]
感觉不应该啊，如果你实在要改的话，直接在train_baseline.py里面的 dcganDataset这个类里面改，这个类是我自己定义的一个图片读取的类,  你可以根据这个修改，  你把这个逻辑看懂后， 对于pytorch这个框架，几乎任何一种数据读取方式就都会了

**Comment by RobinWenqian** [comment]
好的好的！十分感谢！

**Comment by RobinWenqian** [comment]
![image](https://user-images.githubusercontent.com/18494091/43854815-e175786a-9b3b-11e8-9930-fa5b23777ddb.png)
我找到了怎么在读图时候带上0l，但是又发现了一个问题，就是会读到明显不属于数据集里面的文件夹名称，就比如说这个图片里面的5500，检查了dcganDataset这个类，不知道问题出在哪里了

**Comment by qiaoguan** [comment]
检查下你的数据是不是有问题，还有文件夹的名字

**Comment by RobinWenqian** [comment]
文件夹什么的就是下载下来数据集之后用prepare.py和changeIndex.py处理过后的

**Comment by RobinWenqian** [comment]
您好，这里我有点不太懂，这一句我不太懂为什么temp里面folder要加下划线再加filename
![image](https://user-images.githubusercontent.com/18494091/44026803-334d57c6-9eec-11e8-9760-4ebe8ee70aa4.png)
运行就会出现这个报错，因为数据经过changeIndex.py之后文件夹名称应该是xxx而不是xxx_
![image](https://user-images.githubusercontent.com/18494091/44026997-d0de238a-9eec-11e8-8cf7-e5277ed484a2.png)

 之后我如果把下划线去掉，读文件夹倒是没问题，但读到图片时就会少掉图片名最前面的1或者0. 比如291里面有0828xxxxxx.jpg, 读的时候就会读828xxxx.jpg然后报错说没有这个文件

**Comment by qiaoguan** [comment]
temp里面folder加上下划线再加上filename是我为了解析出文件的名字及其对应存储的位置，你不用下划线用其他符号都行，文件夹的名字表示文件夹中图片的label,  因为生成的图片和原始的训练图片的损失函数不同，所以我用了一个flag来进行区分判断，

**Comment by RobinWenqian** [comment]
好的，十分感谢！我去改改试试

**Comment by RobinWenqian** [comment]
彻底将读文件的方式更改了，用了pytorch标准库的ImageFolder类。正在跑结果，谢谢帮助

**Comment by Meimeiainaonao** [comment]
> 彻底将读文件的方式更改了，用了pytorch标准库的ImageFolder类。正在跑结果，谢谢帮助

同学你好，我想问一下你读文件的方式是如何更改的，我现在读生成的图像出现了下面的问题，我已经更改过了但是还是不行，希望同学可以帮我，非常感谢！

[https://github.com/qiaoguan/Person-reid-GAN-pytorch/issues/26](url)
