### ISSUE TITLE
The 2stream implementation in pytorch

### ISSUE THREAD

**Issue by jpainam** [qiaoguan/Person-reid-GAN-pytorch#2]
Hi!
Thanks for the baseline implementation in pytorch. In their [repo](https://github.com/layumi/Person-reID_GAN); the evaluation was also done using the 2stream implementation [identification + verification](https://github.com/layumi/2016_person_re-ID) model.
I want to know if your repo can  provide the implementation (model + evaluation code) for 2stream model
Thanks

**Comment by qiaoguan** [comment]
my baseline is not the same as that baseline,  its based on Residual Networks(or DenseNet),  and i do not implement the identification+verification model.  if you are interested in,  you can implement it!
