### ISSUE TITLE
Single query evaluation code not available

### ISSUE THREAD

**Issue by jpainam** [qiaoguan/Person-reid-GAN-pytorch#7]
Thank for such code. I reproduced the training and the evaluation and confirm the results to be `+-1%`  equal to the reported results. My result for 24000 generated test
`Rank@1:0.908551 Rank@5:0.969121 Rank@10:0.981591 mAP:0.787033`
These are Multi Query evaluation. You reported Single Query Evaluation in your readme.
Can you share the code trick to get the Single Query evaluation?
Thank

**Comment by qiaoguan** [comment]
i do not provide single query evaluation,  there results are  trained by single or multi GPU,  and single GPU training is better!
