### ISSUE TITLE
multi query vs single query - your results seem reversed

### ISSUE THREAD

**Issue by jpainam** [qiaoguan/Person-reid-GAN-pytorch#9]
Hi!
Most paper report multi query evaluation greater than single query evaluation. Your evaluation results show the contrary. Didn't reverse the order of the results?
And please confirm if the evaluation code you provided is for single query evaluation or muti query

Thanks and great code.

**Comment by qiaoguan** [comment]
sorry to reply late, you may understand wrong,  its true that the multi query evaluation is greater than single query evaluation,   while in my experiment ,   the multi  means   we trained the model by multi-GPU ,  not means multi query evaluation result,   and so did the single...     
hope it helped you!

**Comment by qiaoguan** [comment]
sorry to reply late,   you may understand wrong,   its true that the multi query evaluation result is mostly better than the single query evaluation,   while in my experiment,   the single means that we trained the model by single GPU,  not the single query evaluation,   and so is for the multi.        Hope it helps you!

**Comment by jpainam** [comment]
I go your point. Thank you.
